### ISSUE TITLE
Expose Initial Value

### ISSUE THREAD

**Issue by codekrafter** [natintosh/intl-phone-number-input#28] opened 2020-04-01 22:09 UTC
I am currently using this in a form where I need to set the initial value. Would you be able to expose that at the user level?

**Comment by codekrafter** [comment] 2020-04-01 22:39
This is currently doable with a text controller but it would be nice to have this be dedicated field to avoid the overhead of a text controller

**Comment by SpencerRiddering** [comment] 2020-04-06 06:02
If I try to use the text controller method though, the phone number isn't formatted initially (no hyphens) by the form field. I don't see a way to utilize AsYouTypeFormatter for use when preparing my initial value list.

**Comment by codekrafter** [comment] 2020-04-07 00:52
@SpencerRiddering I have the same issue

**Comment by bscottsmith** [comment] 2020-04-07 01:15
You will need to call the formatter directly and set the text controller. Something like:
```
PhoneNumberUtil.formatAsYouType(phoneNumber: "5555551212", isoCode: "US").then((formattedPhone) => _phoneInputController.text = formattedPhone);
```
You would either do that in your initState(), or if it's stateless you could use a FutureBuilder to do it.

**Comment by Abhishek01039** [comment] 2020-04-08 10:18
hii @bscottsmith when I set the textController to InternationalPhoneNumberInput then it will give me an error like ```texteditingcontroller was used after being disposed```
I am not using the dispose method anywhere then also I am getting this error

**Comment by SpencerRiddering** [comment] 2020-04-08 14:51
> You will need to call the formatter directly and set the text controller. Something like:
> 
> ```
> PhoneNumberUtil.formatAsYouType(phoneNumber: "5555551212", isoCode: "US").then((formattedPhone) => _phoneInputController.text = formattedPhone);
> ```
> 
> You would either do that in your initState(), or if it's stateless you could use a FutureBuilder to do it.

For those following along at time, in order to do this you need to add package [libphonenumber](https://pub.dev/packages/libphonenumber) to your pubspec.yaml since PhoneNumberUtil is not exported by the intl-phone-number-input package.

**Comment by bscottsmith** [comment] 2020-04-08 15:13
Yes @Abhishek01039, you hit issue #26. Luckily it was just patched :)

**Comment by natintosh** [comment] 2020-04-08 15:21
> For those following along at time, in order to do this you need to add package [libphonenumber](https://pub.dev/packages/libphonenumber) to your pubspec.yaml since PhoneNumberUtil is not exported by the intl-phone-number-input package. 

You could call this static method 

PhoneNumber.getParsableNumber

**Comment by SpencerRiddering** [comment] 2020-04-09 16:22
I think this issue could benefit from a concrete example. Say I have the following phone number which I've persisted to my database:  +19162255887

When I go to display it using the InternationalPhoneNumberInput widget, I need to do two things: 

 1. Get the dial code (+1 in this case), figure out what the corresponding country ISO code is ('US'), and then set the initialCountry2LetterCode parameter with this value. 
 
 2. Format the remaining phone number (9162255887), and assign it to the initial value for the InternationalPhoneNumberInput widget. A formatted phone number in this case looks like this: 916-225-5887

Step one is easily done by PhoneNumber.getRegionInfoFromPhoneNumber(..)

Step two is not so easy. PhoneNumber.getParsableNumber('+19162255887', '+1') produces: 9162255887 and so it's not a solution for step two. What is needed is to call PhoneNumberUtil.formatAsYouType(..) with the phoneNumber of PhoneNumber.getParsableNumber() and the country ISO code from PhoneNumber.getRegionInfoFromPhoneNumber(..). Here is an example: 

        String originalPhoneNumber = '+19162255887';
        PhoneNumber numberRegionInfo = await PhoneNumber.getRegionInfoFromPhoneNumber(originalPhoneNumber);
        String parsableNumber = PhoneNumber.getParsableNumber(originalPhoneNumber, numberRegionInfo.dialCode);
        String formattedNumber = await PhoneNumberUtil.formatAsYouType(phoneNumber: parsableNumber, isoCode: numberRegionInfo.isoCode);
        print(formattedNumber); // (916) 225-5887

This works in general, but has one issue: InternationalPhoneNumberInput formats dial code with a hyphen whereas PhoneNumberUtil.formatAsYouType(..) formats with parens. 

  916-225-5887     vs     (916) 225-5887

Can someone explain why different formattings are produced? I seem to be using the same version of libphonenumber as intl-phone-number-input is (1.0.1)

**Comment by natintosh** [comment] 2020-04-09 19:39
Oh, I grab what you are trying to say. I actually thought I implemented something like that I'll work on it. 

>  This works in general, but has one issue: InternationalPhoneNumberInput formats dial code with a hyphen whereas PhoneNumberUtil.formatAsYouType(..) formats with parens.
>
>916-225-5887 vs (916) 225-5887

For the difference in the format, I do not know the cause of that I'll check it out but I wrote a custom TextInputFormatter that uses the PhoneNumberUtil.formatAsYouType(..) >> [Here](https://github.com/natintosh/intl-phone-number-input/blob/master/lib/src/utils/formatter/as_you_type_formatter.dart)

**Comment by natintosh** [comment] 2020-04-11 20:14
Hi @SpencerRiddering, I think I finally know what's going on. 

On the getRegionInfo for libphonenumber package,
```dart
  private void handleGetRegionInfo(MethodCall call, Result result) {
    final String phoneNumber = call.argument("phone_number");
    final String isoCode = call.argument("iso_code");

    try {
      Phonenumber.PhoneNumber p = phoneUtil.parse(phoneNumber, isoCode.toUpperCase());
      String regionCode = phoneUtil.getRegionCodeForNumber(p);
      String countryCode = String.valueOf(p.getCountryCode());
      String formattedNumber = phoneUtil.format(p, PhoneNumberUtil.PhoneNumberFormat.NATIONAL);

      Map<String, String> resultMap = new HashMap<String, String>();
      resultMap.put("isoCode", regionCode);
      resultMap.put("regionCode", countryCode);
      resultMap.put("formattedPhoneNumber", formattedNumber);
      result.success(resultMap);
    } catch (NumberParseException e) {
      result.error("NumberParseException", e.getMessage(), null);
    }
  }
```

on this line 

```dart 
String formattedNumber = phoneUtil.format(p, PhoneNumberUtil.PhoneNumberFormat.NATIONAL);
```

It uses the National format.

While AsYouTypeFormatter doesn't have any specific format and its use both "-" and " " as its separator. 
For the new changes you requested I am going to update the getParsableNumber to accepts two Strings phoneNumber and isoCode and return the formatted phoneNumber String

**Comment by SpencerRiddering** [comment] 2020-04-13 16:44
Thanks @natintosh I think that will work for me. 

I didn't mean to distract from the issue originally reported by @codekrafter regarding the desire for an initial value parameter to the InternationalPhoneNumberInput widget. Example: 

    PhoneNumber initialPhoneNumber = PhoneNumber('+19162255887');
    InternationalPhoneNumberInput(
        initialValue: initialPhoneNumber,
        ...
    )

initialCountry2LetterCode wouldn't be required in this case since it's already contained within the  PhoneNumber object.

**Comment by natintosh** [comment] 2020-04-23 15:50
Hi guys I just published an update thank you for your contributions 👍

**Closed by natintosh** 2020-04-23 15:50 UTC

**Comment by abdulwahid24** [comment] 2020-05-03 10:51
@natintosh I highly appreciate your contribution, I upgraded with the latest package but I couldn't figure out how can we set initialValue because previously I was setting on the text controller.
```
PhoneNumber.getRegionInfoFromPhoneNumber(widget.needy.phone).then((phoneNumber){
      setState(() {
        phoneText.text = phoneNumber.parseNumber();
      });
    });
```
But now, I am facing issue as in edit form, When open the form the phone field with valid phone number shows invalid.
![WhatsApp Image 2020-05-03 at 12 47 29 PM](https://user-images.githubusercontent.com/4718496/80912368-cf147500-8d3c-11ea-9534-01bef7ef377c.jpeg)

**Comment by natintosh** [comment] 2020-05-03 11:04
Sorry for the inconvenience @abdulwahid24 and the sudden  breaking change, I updated the package to support a new initial value property that accepts a PhoneNumber object, so you basically use setState on your initial value object reference


```dart
PhoneNumber number =
        await PhoneNumber.getRegionInfoFromPhoneNumber(phoneNumber, 'US');

    setState(() {
      this.number = number;
    });
```

**Comment by abdulwahid24** [comment] 2020-05-03 11:13
Okay, Let me try out this.

**Comment by abdulwahid24** [comment] 2020-05-03 11:21
Thank a ton @natintosh, It worked now. I was struggling for a few hours.

**Comment by abdulwahid24** [comment] 2020-05-03 11:31
@natintosh I found the same issue on opening a new empty form, as it shouldn't validate initially without typing anything in the phone field.

![WhatsApp Image 2020-05-03 at 1 22 56 PM](https://user-images.githubusercontent.com/4718496/80913111-69c38280-8d42-11ea-84ee-02a09ea651cd.jpeg)

**Comment by abdulwahid24** [comment] 2020-05-03 11:45
Also, the phone field gets clear after toggling a dialog popup.

**Comment by abdulwahid24** [comment] 2020-05-03 14:14
I fixed the issue by putting a 
```
textFieldController: phoneText,
ignoreBlank: true,
```

**Comment by b02505048** [comment] 2020-06-09 10:53
> Sorry for the inconvenience @abdulwahid24 and the sudden breaking change, I updated the package to support a new initial value property that accepts a PhoneNumber object, so you basically use setState on your initial value object reference
> 
> ```dart
> PhoneNumber number =
>         await PhoneNumber.getRegionInfoFromPhoneNumber(phoneNumber, 'US');
> 
>     setState(() {
>       this.number = number;
>     });
> ```

Hi @natintosh, I saw your example, the phoneNumber is a fixed number.
My question is how to retrieve the `phoneNumber` from user input and use it in `PhoneNumber.getRegionInfoFromPhoneNumber(phoneNumber, 'US')`, your help will be appreciated!!! Thank you!!
