### ISSUE TITLE
Severe: _InputWidget disposes any controller widget you pass to, causing errors if the widget it's parented to to error

### ISSUE THREAD

**Issue by SwissCheese5** [natintosh/intl-phone-number-input#34] opened 2020-04-22 10:02 UTC
this code exists in _InputWidget

```dart
  @override
  void initState() {
    Future.delayed(Duration.zero, () => _loadCountries(context));
    controller = widget.textFieldController ?? TextEditingController();
    controller.addListener(_phoneNumberControllerListener);
    super.initState();
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }
```
This is understandable behavior if the controller is null and you make a default one.
But if you pass your own controller, it will dispose it for you.
This means, in my Widget holding several controllers and a fields in a ListView, you have to scroll down. If you scroll down, the ListView disposes the widgets that are NOT in view. So if the phone number input widget is disposed OUTSIDE the screen-view, then the number input widget will dispose of the controller you passed to it.

This causes huge errors. The plugin should ONLY dipose its DEFAULT controller, not the manually passed in one. The user must dispose of that by themselves, just like all of flutter's controller handling.

![2020-04-22_13-00-39](https://user-images.githubusercontent.com/7407478/79968874-648c4b00-8499-11ea-831f-935c2ec90045.gif)

```
The following assertion was thrown building _DefaultInheritedProviderScope<InputProvider>(value: Instance of 'InputProvider', listening to value):
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
The relevant error-causing widget was: 
  InternationalPhoneNumberInput
```

**Comment by bscottsmith** [comment] 2020-04-22 17:04
This is a duplicate of #26

**Comment by natintosh** [comment] 2020-04-23 15:55
Hi @SwissCheese5 thanks for raising this issue but this a duplicate of #26 an update with the fix has been published thanks

**Closed by natintosh** 2020-04-23 15:55 UTC
